apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: frontend-team
  namespace: argocd

spec:
  description: this project holds a new frontend app 
  sourceRepos:
    - https://github.com/opsbyabdullah/argocd-demos.git
  destinations:
    - namespace: frontend-app
      server: https://kubernetes.default.svc 
  clusterResourceWhitelist:
    - group: "*" 
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*" 
      kind: "*"
  roles:                       # Define roles for RBAC within this Project
    - name: frontend-admins    # Role name  
      description: Admins for frontend team
      policies:                # Policies associated with this role
        # syntax: - p, proj:<project-name>:<role-name>, applications, <action>, <project>/<app-name>, permission(allow|deny)
        - p, proj:frontend-team:frontend-admins, applications, *, frontend-team/*, allow  # Full access to all apps in this Project, Here p = policy, proj = project, applications = resource, * = action (all actions), frontend-team/* = resource name pattern, allow = effect (allow or deny)