kind: Secret
apiVersion: v1
metadata: 
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  email-username: "mabdullahn763@gmail.com"
  email-password: "<YOUR_EMAIL_PASSWORD>"